"""release candidate

Revision ID: 2d6816f49c20
Revises: 
Create Date: 2018-06-04 16:13:40.628077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6816f49c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_form', sa.Column('fecha_fin', sa.DateTime(), nullable=True))
    op.add_column('gas_form', sa.Column('fecha_inicio', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gas_form', 'fecha_inicio')
    op.drop_column('gas_form', 'fecha_fin')
    # ### end Alembic commands ###
